src/Entity/Note.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\DateFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use App\Repository\NoteRepository;
use App\Utils\NameableTrait;
use App\Utils\TimestampableTrait;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;


#[ORM\Entity(repositoryClass: NoteRepository::class)]
#[ORM\EntityListeners(
    ["App\EntityListener\TimestampListener", "App\EntityListener\AuthorListener", "App\EntityListener\SlugListener"]
)]
#[UniqueEntity(fields: ["slug"], message: "This slug is already used")]
#[ApiResource(
    collectionOperations: [
    'get' => [
        'normalization_context' => ['groups' => ['note:read']],
    ],
],
    itemOperations: [
    'get' => [
        'normalization_context' => ['groups' => ['note:read']],
        ],
    ],
)]
#[ApiFilter(SearchFilter::class, properties: [
    'title' => 'ipartial',
    'slug' => 'iexact',
    'course.title' => 'ipartial',
    'course.code' => 'iexact',
    'author.firstName' => 'ipartial',
    'author.lastName' => 'ipartial',
])]
#[ApiFilter(DateFilter::class, properties: ['wroteAt'])]
class Note
{
    use TimestampableTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    private int $id;

    #[ORM\Column(type: "string", length: 127)]
    #[NotBlank]
    #[Length(max: 127)]
    #[Groups(["note:read"])]
    private string $title;

    #[ORM\Column(type: "string", length: 127, unique: true)]
    private string $slug;

    #[ORM\Column(type: "string", length: 127, nullable: true)]
    #[NotBlank]
    #[Length(max: 127)]
    #[Groups(["note:read"])]
    private string $shortDescription;

    #[ORM\Column(type: "text")]
    #[NotBlank]
    #[Length(max: 2000)]
    #[Groups(["note:read"])]
    private string $description;

    #[ORM\ManyToOne(targetEntity: Course::class, inversedBy: "notes")]
    #[ORM\JoinColumn(nullable: false)]
    #[NotNull]
    #[Groups(["note:read"])]
    private Course $course;

    #[ORM\OneToOne(targetEntity: NoteFile::class, cascade: ["persist", "remove"])]
    #[ORM\JoinColumn(nullable: false)]
    private NoteFile $noteFile;

    #[ORM\OneToMany(mappedBy: "note", targetEntity: Comment::class, orphanRemoval: true)]
    private iterable $comments;

    #[ORM\OneToMany(mappedBy: "note", targetEntity: Report::class, orphanRemoval: true)]
    private iterable $reports;

    #[ORM\OneToMany(mappedBy: "note", targetEntity: Review::class, orphanRemoval: true)]
    private iterable $reviews;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: "notes")]
    #[ORM\JoinColumn(nullable: false)]
    #[Groups(["note:read"])]
    private User $author;

    #[ORM\Column(type: "datetime")]
    #[NotNull]
    #[Groups(["note:read"])]
    private DateTimeInterface $wroteAt;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->reports = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->title;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): void
    {
        $this->slug = $slug;
    }

    public function getShortDescription(): ?string
    {
        return $this->shortDescription;
    }

    public function setShortDescription(string $shortDescription): self
    {
        $this->shortDescription = $shortDescription;

        return $this;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCourse(): Course
    {
        return $this->course;
    }

    public function setCourse(Course $course): self
    {
        $this->course = $course;

        return $this;
    }

    public function getNoteFile(): NoteFile
    {
        return $this->noteFile;
    }

    public function setNoteFile(NoteFile $noteFile): self
    {
        $this->noteFile = $noteFile;

        return $this;
    }

    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setNote($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getNote() === $this) {
                $comment->setNote(null);
            }
        }

        return $this;
    }

    public function getReports(): Collection
    {
        return $this->reports;
    }

    public function addReport(Report $report): self
    {
        if (!$this->reports->contains($report)) {
            $this->reports[] = $report;
            $report->setNote($this);
        }

        return $this;
    }

    public function removeReport(Report $report): self
    {
        if ($this->reports->removeElement($report)) {
            // set the owning side to null (unless already changed)
            if ($report->getNote() === $this) {
                $report->setNote(null);
            }
        }

        return $this;
    }

    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setNote($this);
        }

        return $this;
    }

    #[Groups(["note:read"])]
    public function getAverageScore(): float
    {
        $sum = 0.0;
        foreach ($this->reviews as $review) {
            $sum += $review->getScore();
        }

        return count($this->reviews) > 0 ? $sum / count($this->reviews) : 0;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getNote() === $this) {
                $review->setNote(null);
            }
        }

        return $this;
    }

    public function getAuthor(): User
    {
        return $this->author;
    }

    public function setAuthor(User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getWroteAt(): DateTimeInterface
    {
        return $this->wroteAt;
    }

    public function setWroteAt(DateTimeInterface $wrote_at): self
    {
        $this->wroteAt = $wrote_at;

        return $this;
    }
    
    public function getPath() : string
    {
        $path = $this->course->getStudy()->getFaculty()->getSchool()->getTitle() . '/' .
            $this->course->getStudy()->getFaculty()->getTitle() . '/' .
            $this->course->getStudy()->getTitle() . '/' .
            $this->course->getTitle();
        return str_replace(' ', '-', $path);
    }
}

templates/component/card/card-course.html.twig
<li class="inline-block rounded-lg shadow overflow-hidden h-full hover:shadow-lg transform hover:scale-105 transition duration-300
           bg-neutral-focus text-neutral-content">
    <div class="h-full">
        {% if isDeletable %}
        <div class="flex flex-row-reverse">
            <div class="pr-4 pt-4 hover:text-red-500">
                <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                    <path fill="currentColor" d="M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2C6.47,2 2,6.47 2,12C2,17.53 6.47,22 12,22C17.53,22 22,17.53 22,12C22,6.47 17.53,2 12,2M14.59,8L12,10.59L9.41,8L8,9.41L10.59,12L8,14.59L9.41,16L12,13.41L14.59,16L16,14.59L13.41,12L16,9.41L14.59,8Z" />
                </svg>
            </div>
        </div>
        {% endif %}
        <a href="{{ path }}">
            <div class="px-8 h-full {{ isDeletable ? 'pb-6' : 'py-6' }}">
                <h2 class="text-2xl font-bold">{{ item.title }}</h2>
                <div class="flex justify-between text-gray-600 text-sm font-medium flex mb-4 mt-2 text-primary">
                    <p>
                        <i class="fas fa-book"></i>
                        <span>{{ item.code }}</span>
                    </p>
                    <p>{{ item.notes | length }} {% trans %}notes{% endtrans %}</p>
                </div>
            </div>
        </a>
    </div>
</li>

templates/component/card/card-note.html.twig
<li class="rounded-lg shadow overflow-hidden h-full hover:shadow-lg transform hover:scale-105 transition duration-300
           bg-neutral-focus text-neutral-content">
    <a href="{{ path }}" class="relative h-full">
        <div class="py-10 px-8 flex flex-col justify-between h-full">
            <div>
                <h2 class="text-2xl font-bold truncate">{{ item.title }}</h2>
                <div class="text-primary text-sm font-medium flex mb-4">
                    <span>
                        {{ item.author.firstName }} {{ item.author.lastName }}
                    </span>
                </div>
            </div>

            <p class="break-words text-justify">
                {{ item.shortDescription }}
            </p>

            <div class="mt-10 flex justify-between items-center">
                <span class="mr-4 text-primary">
                    <i class="fas fa-clock"></i>
                    {{ item.createdAt | ago }}
                </span>

                {% if item.averageScore != 0 %}
                <span class="text-warning">
                    {{ item.averageScore | round }}
                    <i class="fas fa-star"></i>
                    ({{ item.reviews | length }})
                </span>
                {% endif %}
            </div>
        </div>
    </a>
</li>

templates/component/card/card-simple.html.twig
<li class="inline-block rounded-lg shadow overflow-hidden h-full hover:shadow-lg transform hover:scale-105 transition
           bg-neutral-focus text-neutral-content">
    <a href="{{ path }}">
        <div class="h-full">
            <div class="py-10 px-8 h-full">
                <h2 class="text-2xl font-bold">{{ item.title }}</h2>
            </div>
        </div>
    </a>
</li>

templates/component/card/card-stat.html.twig
<div class="rounded-lg shadow overflow-hidden h-full p-8
            {{ isDark is defined and isDark ?
                "dark:bg-gray-900 bg-purple-800" : "bg-purple-100 dark:bg-gray-800 dark:text-gray-100" }}">
    <div class="h-full">
        <h2 class="text-3xl font-bold
                {{ isDark is defined and isDark
                    ? "text-white dark:text-green-400" : "text-purple-700 dark:text-green-400" }}">
            {{ title | trans }}
        </h2>
        <p class="text-xl font-semibold
                {{ isDark is defined and isDark
                    ? "text-purple-300 dark:text-white" : "" }}">
            {{ data }}
        </p>
    </div>
</div>